spring:
  application:
    name: eureka-turbine

# embedded server configuration
server:
  port: 8083

eureka:
  instance:
    hostname: localhost
    metadata-map:
      cluster: main
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

turbine:
  appConfig: EUREKA-SERVICE
  clusterNameExpression: metadata['cluster']