spring:
  application:
    name: eureka-client

# embedded server configuration
server:
  port: 8080
 # contextPath: /client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/