spring:
  application:
    name: eureka-service

# embedded server configuration
server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    metadata-map:
      cluster: main
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/